version: '2.2'

services:
  rabbitmq:
      image: rabbitmq:latest
      container_name: rabbitmq
      ports:
        - "15691:15691"
        - "15672:15672"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"