version: '2.2'

services:
  redis:
      image: redis:latest
      container_name: redis
      ports:
        - "6379:6379"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"