version: '2.2'

services:
  mysql:
      image: mysql:5.6.47
      container_name: dev-mysql2
      ports:
        - "3307:3307"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"