version: '2.2'

services:
  mysql:
      image: mysql:latest
      container_name: mysql-course-udemy
      ports:
        - "3306:3306"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
        - "MYSQL_ROOT_PASSWORD=mysql#docker23"