version: '2.2'

services:
  neo4j:
      image: neo4j:latest
      container_name: neo4j
      ports:
        - "7473:7473"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"